# Generated by Django 3.2.5 on 2022-09-23 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_create_date_alter_job_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 13, 32, 17, 57572), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 13, 32, 17, 57572), verbose_name='修改时间'),
        ),
    ]
