# Generated by Django 4.1.1 on 2022-09-19 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='hr_interviewer',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='second_interviewer',
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_interviewer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_interviewer_user', to=settings.AUTH_USER_MODEL, verbose_name='一面面试官'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='hr_interviewer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_interviewer_user', to=settings.AUTH_USER_MODEL, verbose_name='人力资源官'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_interviewer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_interviewer_user', to=settings.AUTH_USER_MODEL, verbose_name='二面面试官'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hr_advantage',
            field=models.TextField(blank=True, max_length=1024, verbose_name='HR-优势'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hr_disadvantage',
            field=models.TextField(blank=True, max_length=1024, verbose_name='HR-顾虑和不足'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_advantage',
            field=models.TextField(blank=True, max_length=1024, verbose_name='优势'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_disadvantage',
            field=models.TextField(blank=True, max_length=1024, verbose_name='顾虑和不足'),
        ),
    ]
