# Generated by Django 4.1.1 on 2022-09-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_remove_candidate_hr_interviewer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': [('export', 'Can export candidate list'), ('notify', 'notify interviewer for candidate review')], 'verbose_name': '应聘者', 'verbose_name_plural': '应聘者'},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_learning_ability',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='分数范围1-9', max_digits=2, null=True, verbose_name='学习能力得力'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_professional_competency',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='分数范围1-9', max_digits=2, null=True, verbose_name='专业能力得分'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='分数范围1-9', max_digits=2, null=True, verbose_name='初试分'),
        ),
    ]
